services:
  postgres:
    container_name: techtest_db
    image: postgres:15
    environment:
      POSTGRES_USER: techtest
      POSTGRES_PASSWORD: t3cht3st
      POSTGRES_DB: techtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: techtest_redis
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    environment:
      - RUSTFS_ACCESS_KEY=minioadmin
      - RUSTFS_SECRET_KEY=minioadmin
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: techtest_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: techtest
      RABBITMQ_DEFAULT_PASS: t3cht3st
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  rustfs_data:
  rustfs_logs:
